/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.1--ijk0.6.0--20160715--001"
#endif /* AVUTIL_FFVERSION_H */
